version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    container_name: taller_db
    restart: always
    ports:                  # <--- ESTO ES LO QUE TE FALTA
      - "5432:5432"         # <--- ESTO ES CRUCIAL
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taller_net

  # 2. Tu Backend (NestJS)
  backend:
    build: .
    container_name: taller_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - DB_SYNCHRONIZE=true
    depends_on:
      - db
    networks:
      - taller_net

  # 3. NocoDB (Panel Admin)
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    ports:
      - "8081:8080"
    environment:
      NC_DB: "pg://db:5432?u=${DB_USERNAME}&p=${DB_PASSWORD}&d=noco_meta"
    depends_on:
      - db
    networks:
      - taller_net

volumes:
  postgres_data:
  nc_data:

networks:
  taller_net:


